#! /bin/ksh
# Executes a VCLOD script (Variable Config, Locking, Operation, and Destination) with all
# the setup that entails. See the README for an overview of VCLODs.
#
# Usage:
# ./vclod_run_script /path/to/script

# Argument validation -- Continued later
[ -z "$VCLOD_BASE_DIR" ] && . "$(dirname $(readlink -f $(which $0)))/vclod_loadenv"
: ${VCLOD_BASE_DIR:?} ${VCLOD_FORCE_SETUP_SQL:=0} ${1:?The full path of a file to process is a required positional argument}
S=$([ $(basename $1) == "$1" ] && echo "./$1" || echo "$1")
[ -s "$S" ] || { echo >&2 The positional argument must be a non-empty file; exit 1; }

# respect local config file
[ -f "`dirname $S`/config" ] && . "`dirname $S`/config"

. "${VCLOD_BASE_DIR%/}/vclod_get_semaphore"
. "${VCLOD_BASE_DIR%/}/vclod_stdio2log"

[[ $S =~ .*\.sh$ ]] && head -1 $S | grep '^#!' | grep -v 'ksh' | awk 'NR == 1 {print "[WARNING] This is a KSH framework, and the sh files are sourced, so only KSH dialects are supported. For others, use the .shebang."}' >&2

# Connection parameters are required, but can be set either in the env or the current directory's config file
: ${DEBUG_SHOULD_TIME_IT:=$([ -t 1 ] ; echo $?)}
if [[ $S =~ .*\.sql(\..*)? || $VCLOD_FORCE_SETUP_SQL != 0 ]]; then
  : ${VCLOD_ENGINE:=mysql}
  [ -f "${VCLOD_BASE_DIR%/}/connections/$VCLOD_ENGINE" ] || { echo >&2 "Unknown engine type $VCLOD_ENGINE" ; exit 1 ; }
  for v in HOST DB USER PASSWORD; do cat << EOF | . /dev/stdin ; done
VCLOD_$v=\${VCLOD_$(echo $VCLOD_ENGINE | tr '[:lower:]' '[:upper:]')_$v:=\${VCLOD_$v:?}}
EOF
  export SRC="$(cat ${VCLOD_BASE_DIR%/}/connections/$VCLOD_ENGINE | HOST=$VCLOD_HOST DB=$VCLOD_DB USER=$VCLOD_USER PWORD=$VCLOD_PASSWORD envsubst)"
else
  export SRC='eval : ${VCLOD_FORCE_SETUP_SQL:?required to use SRC if .sql is not in the extension path}'
fi
if [[ $S =~ .*\.dst(\..*)? || $VCLOD_FORCE_SETUP_SQL != 0 ]]; then
  : ${VCLOD_DST_ENGINE:=${VCLOD_ENGINE:-mysql}}
  [ -f "${VCLOD_BASE_DIR%/}/connections/$VCLOD_DST_ENGINE" ] || { echo >&2 "Unknown destination engine type $VCLOD_DST_ENGINE" ; exit 1 ; }
  for v in HOST DB USER PASSWORD; do cat << EOF | . /dev/stdin ; done
: \${VCLOD_DST_${v}:=\${VCLOD_$(echo $VCLOD_DST_ENGINE | tr '[:lower:]' '[:upper:]')_$v:-\${VCLOD_$v:?}}}
EOF
  export DST="$(cat ${VCLOD_BASE_DIR%/}/connections/$VCLOD_DST_ENGINE | HOST=$VCLOD_DST_HOST DB=$VCLOD_DST_DB USER=$VCLOD_DST_USER PWORD=$VCLOD_DST_PASSWORD envsubst)"
else
  export DST='eval : ${VCLOD_FORCE_SETUP_SQL:?required to use DST if .dst is not in the extension path}'
fi

export INPUT_DIR="$(dirname $S)"

operation(){
  next="${1%.*}"
  [[ "$1" == "$next" ]] && cat && return # the cat connects stdin to stdout, note that the error case below does not.
  extension="${1##*.}"
  ext="${extension%%-*}"
  ext_opt="$([ $extension = $ext ] || echo ${extension#*-})"
  base_filename="${1%%.*}"
  op_ext_file="${VCLOD_BASE_DIR%/}/extensions/$ext"
  test -f $op_ext_file || { echo "Unknown file type $ext" >&2 ; exit 99 ; }
  . $op_ext_file | operation $next
}

ret=0
[ $DEBUG_SHOULD_TIME_IT == 1 ] && echo "[START] $@"
cat $S | operation $(basename $S) || { ret=$?; echo >&2 "`basename $S` returned $ret"; }
[ $DEBUG_SHOULD_TIME_IT == 1 ] && echo "[FINISH] $@ returned $ret"
exit $ret
