#! /bin/ksh
# Launches all VCLOD batches defined in a directory, running up to VCLOD_JOBS at a time. One of the primary ways of
# launching VCLOD batches.
#
# Usage:
# ./vclod_do_dir /path/to/dir
#

[ -z "$VCLOD_BASE_DIR" ] && . "$(dirname "$(readlink -f "$(which "$0")")")/vclod_loadenv"

# Argument validation
: "${VCLOD_BASE_DIR:?} ${VCLOD_JOBS:=10} ${1:?Missing a directory or file to process} ${OPERATIONS_EMAIL:?}"
[ -d "$VCLOD_BASE_DIR" ] || { echo VCLOD_BASE_DIR must be an existing directory; exit; }
[ -d "$LOG_BASE_DIR" ] || { echo LOG_BASE_DIR must be an existing directory; exit; }
MAIL_ELF="${LOG_BASE_DIR:?}/$$.err"
export MAIL_ELF

if [ -e "$1" ]; then
  find "$@" ! -empty -xtype f -regextype posix-egrep -regex "$VCLOD_FILE_REGEX" | sort | xargs -n1 -r -P"$VCLOD_JOBS" "${VCLOD_BASE_DIR%/}/vclod_run_script"
else
  . "${VCLOD_BASE_DIR%/}/vclod_run_script" 
fi
ret=$?
[ -s "$MAIL_ELF" ] && [ ! -t 1 ] && mail -s "Script error digest on $(hostname)" "$OPERATIONS_EMAIL" <"$MAIL_ELF"
exit $ret
